language: java
install:
 - mvn install -Pgenerate-rest-doc -Dhostname=localhost -Dport=8080
before_install:
 - echo "<settings><servers><server><id>focus-snapshots</id><username>\${env.FOCUS_USER}</username><password>\${env.FOCUS_PASS}</password></server></servers></settings><profile><id>focus</id><activation><activeByDefault>true</activeByDefault></activation><repositories><repository><id>focus-releases</id><name>FOCUS Repository</name><url>http://nexus.focus.fish/nexus/content/repositories/releases/</url><releases><enabled>true</enabled></releases><snapshots><enabled>false</enabled></snapshots></repository><repository><id>focus-snapshots</id><name>FOCUS Snapshot Repository</name><url>http://nexus.focus.fish/nexus/content/repositories/snapshots/</url><releases><enabled>false</enabled></releases><snapshots><enabled>true</enabled></snapshots></repository></repositories></profile></profiles>" > ~/settings.xml
after_success:
 - mvn deploy --settings ~/settings.xml
branches:
  only:
  - swe-dev
