language: java
install:
 - mvn install -Pgenerate-rest-doc -Dhostname=localhost -Dport=8080
before_install:
 - echo "<settings><servers><server><id>focus-snapshots</id><username>\${env.FOCUS_USER}</username><password>\${env.FOCUS_PASS}</password></server></servers></settings>" > ~/settings.xml
after_success:
 - mvn deploy --settings ~/settings.xml
branches:
  only:
  - swe-dev
